name: TypeScript CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

  deploy-test:
    needs: build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Deploy with SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 187.115.149.13
        username: geilsonrm
        port: 8086
        key: ${{ secrets.TEST_SSH_KEY }}
        script: |
          # Preparar diretório
          mkdir -p ~/app
          rm -rf ~/app/*
          
          # Garantir que PM2 está instalado
          npm install -g pm2
          echo "Ambiente preparado"
    
    - name: Sync files
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 187.115.149.13
        username: geilsonrm
        port: 8086
        key: ${{ secrets.TEST_SSH_KEY }}
        source: "dist/,package.json,package-lock.json"
        target: "~/app"
        strip_components: 0
    
    - name: Start Application
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 187.115.149.13
        username: geilsonrm
        port: 8086
        key: ${{ secrets.TEST_SSH_KEY }}
        script: |
          cd ~/app
          npm ci --only=production
          
          # Parar aplicação existente
          pm2 delete app || true
          
          # Iniciar com configurações específicas
          pm2 start dist/index.js \
            --name app \
            --log ~/app/logs/app.log \
            --time \
            --no-autorestart \
            --exp-backoff-restart-delay=100
          
          # Salvar configuração do PM2
          pm2 save
          
          # Mostrar status
          pm2 status
          
          # Mostrar logs iniciais
          sleep 2
          tail -n 20 ~/app/logs/app.log || true

  deploy-prod:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Deploy to Production
      run: |
        echo "Deploy to production server will be configured here"
        # Configuração futura para produção
